export const USERS_DATA = [
    {
        "id": "a786623a50c045cfbc8dc1b5cc8162ff",
        "second_name": "Потапов",
        "name": "Лазарь",
        "middle_name": "Ярославович",
        "adress": "г. Нурлат, бул. Ангарский, д. 6, 924031",
        "passport": "3942 727620",
        "email": "lazar'.potapov@company.ru",
        "date_of_birth": "1958-03-09",
        "age": 68,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Генеральный директор",
        "education": "высшее",
        "department_id": 5,
        "year_of_start_education": "1976",
        "year_of_end_education": "1980",
        "year_of_start_work": "1980"
    },
    {
        "id": "433c96f4fb7f4d13bb40c3026996c66b",
        "second_name": "Беспалов",
        "name": "Селиверст",
        "middle_name": "Гертрудович",
        "adress": "г. Амдерма, наб. Сурикова, д. 6, 093379",
        "passport": "7202 800258",
        "email": "seliverst.bespalov@company.ru",
        "date_of_birth": "1967-01-07",
        "age": 59,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Директор по персоналу",
        "education": "высшее",
        "department_id": 6,
        "year_of_start_education": "1985",
        "year_of_end_education": "1989",
        "year_of_start_work": "1989"
    },
    {
        "id": "4f6c612980034ce0a950bcf117438853",
        "second_name": "Попов",
        "name": "Геннадий",
        "middle_name": "Афанасьевич",
        "adress": "к. Великие Луки, бул. Камский, д. 150, 708253",
        "passport": "9895 324220",
        "email": "gennadij.popov@company.ru",
        "date_of_birth": "1987-06-28",
        "age": 39,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "ИТ-директор",
        "education": "высшее",
        "department_id": 6,
        "year_of_start_education": "2005",
        "year_of_end_education": "2009",
        "year_of_start_work": "2009"
    },
    {
        "id": "306462351f8e420eb9f1b19dd2120e5f",
        "second_name": "Михеев",
        "name": "Чеслав",
        "middle_name": "Харлампович",
        "adress": "п. Нягань, ул. Беляева, д. 149 к. 201, 177164",
        "passport": "4918 745366",
        "email": "cheslav.miheev@company.ru",
        "date_of_birth": "1955-09-06",
        "age": 71,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Финансовый директор",
        "education": "высшее",
        "department_id": 19,
        "year_of_start_education": "1973",
        "year_of_end_education": "1977",
        "year_of_start_work": "1977"
    },
    {
        "id": "27fd7f200b4541a1a0a2210705aba536",
        "second_name": "Селезнев",
        "name": "Нифонт",
        "middle_name": "Евстигнеевич",
        "adress": "к. Кимры, пр. Дорожный, д. 261 к. 89, 878319",
        "passport": "1147 590475",
        "email": "nifont.seleznev@company.ru",
        "date_of_birth": "1960-12-09",
        "age": 65,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Заместитель генерального директора по производству",
        "education": "высшее",
        "department_id": 21,
        "year_of_start_education": "1978",
        "year_of_end_education": "1982",
        "year_of_start_work": "1982"
    },
    {
        "id": "eaf3d0482e32488184ddd1e2296cf898",
        "second_name": "Сорокин",
        "name": "Остромир",
        "middle_name": "Валентинович",
        "adress": "клх Бирск, пер. Амурский, д. 6 к. 1, 061363",
        "passport": "4815 427425",
        "email": "ostromir.sorokin@company.ru",
        "date_of_birth": "1983-12-28",
        "age": 42,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Главный бухгалтер",
        "education": "высшее",
        "department_id": 5,
        "year_of_start_education": "2001",
        "year_of_end_education": "2005",
        "year_of_start_work": "2005"
    },
    {
        "id": "c7b97f4e37ef474a8466c0aa18ac1ab6",
        "second_name": "Осипова",
        "name": "Алина",
        "middle_name": "Евгеньевна",
        "adress": "с. Нефтегорск (Самар.), ул. Химиков, д. 24 стр. 85, 419592",
        "passport": "4050 843929",
        "email": "alina.osipova@company.ru",
        "date_of_birth": "1998-04-30",
        "age": 28,
        "gender": "женский",
        "marital_status": "за мужем",
        "position": "Главный геолог",
        "education": "высшее",
        "department_id": 5,
        "year_of_start_education": "2016",
        "year_of_end_education": "2020",
        "year_of_start_work": "2020"
    },
    {
        "id": "6ead206e01254d0da16e2d96e2dcd377",
        "second_name": "Дорофеева",
        "name": "Евгения",
        "middle_name": "Святославовна",
        "adress": "п. Руза, ш. Малиновое, д. 52, 423750",
        "passport": "6316 157736",
        "email": "evgenija.dorofeeva@company.ru",
        "date_of_birth": "1966-12-04",
        "age": 59,
        "gender": "женский",
        "marital_status": "не замужем",
        "position": "Главный инженер проекта (ГИП)",
        "education": "высшее",
        "department_id": 5,
        "year_of_start_education": "1984",
        "year_of_end_education": "1988",
        "year_of_start_work": "1988"
    },
    {
        "id": "58790121f9f44eb2ab3c0a9a275ef7ed",
        "second_name": "Самсонов",
        "name": "Еремей",
        "middle_name": "Германович",
        "adress": "к. Усть-Катав, алл. Смоленская, д. 940 к. 9, 962143",
        "passport": "8134 366868",
        "email": "eremej.samsonov@company.ru",
        "date_of_birth": "1973-12-09",
        "age": 52,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Главный инженер-разработчик",
        "education": "высшее",
        "department_id": 5,
        "year_of_start_education": "1991",
        "year_of_end_education": "1995",
        "year_of_start_work": "1995"
    },
    {
        "id": "91dde04c782b4f66b19fb1af58de243e",
        "second_name": "Семенов",
        "name": "Тарас",
        "middle_name": "Богданович",
        "adress": "п. Аршан (Бурят.), алл. Щетинкина, д. 9 к. 1/5, 112910",
        "passport": "2723 223891",
        "email": "taras.semenov@company.ru",
        "date_of_birth": "1957-10-20",
        "age": 68,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Главный механик",
        "education": "высшее",
        "department_id": 6,
        "year_of_start_education": "1975",
        "year_of_end_education": "1979",
        "year_of_start_work": "1979"
    },
    {
        "id": "9b4966e37ac1491893b97ebf5ee628a5",
        "second_name": "Пестов",
        "name": "Карл",
        "middle_name": "Вилорович",
        "adress": "с. Анапа, пр. Шишкина, д. 539 к. 7, 905956",
        "passport": "3233 267616",
        "email": "karl.pestov@company.ru",
        "date_of_birth": "1981-03-26",
        "age": 45,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Главный энергетик",
        "education": "высшее",
        "department_id": 6,
        "year_of_start_education": "1999",
        "year_of_end_education": "2003",
        "year_of_start_work": "2003"
    },
    {
        "id": "130edc99ec374e699b2726f50b42e096",
        "second_name": "Хохлов",
        "name": "Иларион",
        "middle_name": "Геннадиевич",
        "adress": "к. Сальск, ул. Кузнечная, д. 75, 045174",
        "passport": "7302 861502",
        "email": "ilarion.hohlov@company.ru",
        "date_of_birth": "1985-07-26",
        "age": 41,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Главный юрист",
        "education": "высшее",
        "department_id": 6,
        "year_of_start_education": "2003",
        "year_of_end_education": "2007",
        "year_of_start_work": "2007"
    },
    {
        "id": "846466ba1f8e4e669f7f708c37c9e109",
        "second_name": "Фомичева",
        "name": "Татьяна",
        "middle_name": "Антоновна",
        "adress": "ст. Нурлат, ш. Энгельса, д. 32 стр. 110, 380846",
        "passport": "8759 232632",
        "email": "tat'jana.fomicheva@company.ru",
        "date_of_birth": "1999-02-13",
        "age": 27,
        "gender": "женский",
        "marital_status": "за мужем",
        "position": "Начальник буровой",
        "education": "высшее",
        "department_id": 11,
        "year_of_start_education": "2017",
        "year_of_end_education": "2021",
        "year_of_start_work": "2021"
    },
    {
        "id": "e2fac3bafca54b678e0243108ec68544",
        "second_name": "Фомичев",
        "name": "Карп",
        "middle_name": "Якубович",
        "adress": "клх Вытегра, ул. Мелиораторов, д. 321 стр. 47, 482374",
        "passport": "6383 423574",
        "email": "karp.fomichev@company.ru",
        "date_of_birth": "1954-07-19",
        "age": 72,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Начальник бюро",
        "education": "высшее",
        "department_id": 11,
        "year_of_start_education": "1972",
        "year_of_end_education": "1976",
        "year_of_start_work": "1976"
    },
    {
        "id": "28c3602b285348ecbb7574989252718d",
        "second_name": "Баранов",
        "name": "Евдоким",
        "middle_name": "Ермолаевич",
        "adress": "клх Снежногорск (Мурм.), пер. Одесский, д. 484 стр. 35, 386557",
        "passport": "4627 476842",
        "email": "evdokim.baranov@company.ru",
        "date_of_birth": "1972-12-31",
        "age": 53,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Начальник караула",
        "education": "высшее",
        "department_id": 11,
        "year_of_start_education": "1990",
        "year_of_end_education": "1994",
        "year_of_start_work": "1994"
    },
    {
        "id": "27d7dd3a012d4bcdaf186b5b49a88f5b",
        "second_name": "Селиверстова",
        "name": "Лариса",
        "middle_name": "Оскаровна",
        "adress": "с. Северобайкальск, бул. Петровский, д. 8/3 стр. 7/9, 455874",
        "passport": "2971 296797",
        "email": "larisa.seliverstova@company.ru",
        "date_of_birth": "1995-05-13",
        "age": 31,
        "gender": "женский",
        "marital_status": "не замужем",
        "position": "Начальник отдела",
        "education": "высшее",
        "department_id": 11,
        "year_of_start_education": "2013",
        "year_of_end_education": "2017",
        "year_of_start_work": "2017"
    },
    {
        "id": "b049ebf30f0648ff9aee1b24cdc85922",
        "second_name": "Соболев",
        "name": "Родион",
        "middle_name": "Григорьевич",
        "adress": "к. Елец, пер. Маркса, д. 337 к. 455, 160780",
        "passport": "6247 871822",
        "email": "rodion.sobolev@company.ru",
        "date_of_birth": "1965-08-16",
        "age": 61,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Начальник партии",
        "education": "высшее",
        "department_id": 11,
        "year_of_start_education": "1983",
        "year_of_end_education": "1987",
        "year_of_start_work": "1987"
    },
    {
        "id": "d8f1c0c824a948139659a32f55703dac",
        "second_name": "Колобов",
        "name": "Самуил",
        "middle_name": "Артемьевич",
        "adress": "д. Голицыно, ш. Войкова, д. 352 к. 1/6, 770400",
        "passport": "1537 259695",
        "email": "samuil.kolobov@company.ru",
        "date_of_birth": "1968-02-05",
        "age": 58,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Начальник пожарной части",
        "education": "высшее",
        "department_id": 12,
        "year_of_start_education": "1986",
        "year_of_end_education": "1990",
        "year_of_start_work": "1990"
    },
    {
        "id": "c0abeeff455143d394d529f58e215610",
        "second_name": "Сергеева",
        "name": "Марфа",
        "middle_name": "Георгиевна",
        "adress": "д. Хасан, пр. Профсоюзный, д. 5/5 стр. 96, 359524",
        "passport": "7579 542818",
        "email": "marfa.sergeeva@company.ru",
        "date_of_birth": "1965-06-24",
        "age": 61,
        "gender": "женский",
        "marital_status": "не замужем",
        "position": "Начальник службы",
        "education": "высшее",
        "department_id": 12,
        "year_of_start_education": "1983",
        "year_of_end_education": "1987",
        "year_of_start_work": "1987"
    },
    {
        "id": "5544689325a14ac98e047bfb172581ee",
        "second_name": "Захаров",
        "name": "Любосмысл",
        "middle_name": "Теймуразович",
        "adress": "с. Салехард, бул. Боровой, д. 364 стр. 6/4, 691108",
        "passport": "2683 507307",
        "email": "ljubosmysl.zaharov@company.ru",
        "date_of_birth": "2001-09-02",
        "age": 25,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Начальник управления",
        "education": "высшее",
        "department_id": 12,
        "year_of_start_education": "2019",
        "year_of_end_education": "2023",
        "year_of_start_work": "2023"
    },
    {
        "id": "784a38f7012f446ab622c356dc792f16",
        "second_name": "Муравьев",
        "name": "Федор",
        "middle_name": "Ааронович",
        "adress": "к. Мураши, ул. Грибоедова, д. 316 стр. 62, 077859",
        "passport": "6187 853844",
        "email": "fedor.murav'ev@company.ru",
        "date_of_birth": "1977-06-29",
        "age": 49,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Начальник участка",
        "education": "высшее",
        "department_id": 12,
        "year_of_start_education": "1995",
        "year_of_end_education": "1999",
        "year_of_start_work": "1999"
    },
    {
        "id": "923896a4db2742d389bc362e4514acb6",
        "second_name": "Афанасьева",
        "name": "Агафья",
        "middle_name": "Алексеевна",
        "adress": "клх Малоярославец, пр. Омский, д. 64 стр. 7, 606766",
        "passport": "3323 713835",
        "email": "agaf'ja.afanas'eva@company.ru",
        "date_of_birth": "1976-02-17",
        "age": 50,
        "gender": "женский",
        "marital_status": "не замужем",
        "position": "Начальник цеха",
        "education": "высшее",
        "department_id": 12,
        "year_of_start_education": "1994",
        "year_of_end_education": "1998",
        "year_of_start_work": "1998"
    },
    {
        "id": "ea5a3589ad014bc7b18ece7b45608dc2",
        "second_name": "Орлов",
        "name": "Наркис",
        "middle_name": "Елисеевич",
        "adress": "с. Арзамас, пр. Хуторской, д. 370 стр. 5, 724407",
        "passport": "4563 977440",
        "email": "narkis.orlov@company.ru",
        "date_of_birth": "1991-08-11",
        "age": 35,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Начальник цеха добычи нефти и газа",
        "education": "высшее",
        "department_id": 13,
        "year_of_start_education": "2009",
        "year_of_end_education": "2013",
        "year_of_start_work": "2013"
    },
    {
        "id": "2419405140b846eda12236a6e91197d0",
        "second_name": "Одинцов",
        "name": "Анатолий",
        "middle_name": "Фокич",
        "adress": "к. Алдан, наб. Ушакова, д. 7/2, 244116",
        "passport": "1655 683047",
        "email": "anatolij.odintsov@company.ru",
        "date_of_birth": "1994-12-23",
        "age": 31,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Руководитель направления",
        "education": "высшее",
        "department_id": 15,
        "year_of_start_education": "2012",
        "year_of_end_education": "2016",
        "year_of_start_work": "2016"
    },
    {
        "id": "14efc6b1ac5a428f8b1c58f6fd77ae3f",
        "second_name": "Мишин",
        "name": "Александр",
        "middle_name": "Ефимьевич",
        "adress": "клх Курчатов, пер. Вольный, д. 97 к. 9/8, 040169",
        "passport": "8789 129026",
        "email": "aleksandr.mishin@company.ru",
        "date_of_birth": "1960-05-24",
        "age": 66,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Руководитель проекта",
        "education": "высшее",
        "department_id": 15,
        "year_of_start_education": "1978",
        "year_of_end_education": "1982",
        "year_of_start_work": "1982"
    },
    {
        "id": "2a35947a447f4515b60ce144bf0423eb",
        "second_name": "Кириллова",
        "name": "Дарья",
        "middle_name": "Рудольфовна",
        "adress": "ст. Белгород, пер. Лунный, д. 467 стр. 7/6, 740800",
        "passport": "9668 530094",
        "email": "dar'ja.kirillova@company.ru",
        "date_of_birth": "2007-07-27",
        "age": 19,
        "gender": "женский",
        "marital_status": "не замужем",
        "position": "Машинист насосных установок",
        "education": "среднее",
        "department_id": 10,
        "year_of_start_education": "2023",
        "year_of_end_education": "2026",
        "year_of_start_work": "2026"
    },
    {
        "id": "65dc1137224848dd9c2cfa5b02942222",
        "second_name": "Копылов",
        "name": "Прокофий",
        "middle_name": "Валентинович",
        "adress": "клх Октябрьское (Хант.), бул. Покровский, д. 265 к. 80, 714455",
        "passport": "5942 781016",
        "email": "prokofij.kopylov@company.ru",
        "date_of_birth": "1962-12-14",
        "age": 63,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Токарь",
        "education": "среднее",
        "department_id": 19,
        "year_of_start_education": "1978",
        "year_of_end_education": "1981",
        "year_of_start_work": "1981"
    },
    {
        "id": "892982dcc95d41cd95bb4a1f74f745c1",
        "second_name": "Дементьев",
        "name": "Амос",
        "middle_name": "Димитриевич",
        "adress": "д. Шелехов, бул. Кленовый, д. 1 к. 5, 366867",
        "passport": "4651 137006",
        "email": "amos.dement'ev@company.ru",
        "date_of_birth": "1991-11-21",
        "age": 34,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Водитель",
        "education": "среднее",
        "department_id": 4,
        "year_of_start_education": "2007",
        "year_of_end_education": "2010",
        "year_of_start_work": "2010"
    },
    {
        "id": "121afc6dd3e940b9b4bb292d23660859",
        "second_name": "Рябов",
        "name": "Аскольд",
        "middle_name": "Артурович",
        "adress": "к. Владивосток, пр. Промышленный, д. 521, 056139",
        "passport": "7072 166212",
        "email": "askol'd.rjabov@company.ru",
        "date_of_birth": "2004-03-03",
        "age": 22,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Ведущий инженер-проектировщик",
        "education": "среднее",
        "department_id": 3,
        "year_of_start_education": "2020",
        "year_of_end_education": "2023",
        "year_of_start_work": "2023"
    },
    {
        "id": "fa1d56245af146ed9f9d442cee316a03",
        "second_name": "Жданов",
        "name": "Гостомысл",
        "middle_name": "Бориславович",
        "adress": "ст. Иваново, алл. Машиностроителей, д. 5/6, 691973",
        "passport": "3754 489995",
        "email": "gostomysl.zhdanov@company.ru",
        "date_of_birth": "1952-11-29",
        "age": 73,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Программист",
        "education": "высшее",
        "department_id": 15,
        "year_of_start_education": "1970",
        "year_of_end_education": "1974",
        "year_of_start_work": "1974"
    },
    {
        "id": "8357d494e3c346de996822c503cd48a7",
        "second_name": "Дроздова",
        "name": "Надежда",
        "middle_name": "Олеговна",
        "adress": "п. Кизилюрт, алл. Сурикова, д. 6/4 к. 2, 344499",
        "passport": "1250 193995",
        "email": "nadezhda.drozdova@company.ru",
        "date_of_birth": "1953-07-13",
        "age": 73,
        "gender": "женский",
        "marital_status": "за мужем",
        "position": "Помощник оператора",
        "education": "среднее",
        "department_id": 14,
        "year_of_start_education": "1969",
        "year_of_end_education": "1972",
        "year_of_start_work": "1972"
    },
    {
        "id": "555a7486e24e441797b3dbb7d7ddb235",
        "second_name": "Дмитриев",
        "name": "Светозар",
        "middle_name": "Феоктистович",
        "adress": "с. Кандалакша, пр. Краснознаменный, д. 85 стр. 526, 753922",
        "passport": "1857 583244",
        "email": "svetozar.dmitriev@company.ru",
        "date_of_birth": "2000-11-12",
        "age": 25,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Специалист по охране труда",
        "education": "высшее",
        "department_id": 17,
        "year_of_start_education": "2018",
        "year_of_end_education": "2022",
        "year_of_start_work": "2022"
    },
    {
        "id": "6492691d90dd42a198d72df24844171e",
        "second_name": "Фокин",
        "name": "Мечислав",
        "middle_name": "Эдгардович",
        "adress": "к. Невинномысск, ул. Московская, д. 25 к. 9/3, 848378",
        "passport": "1290 783490",
        "email": "mechislav.fokin@company.ru",
        "date_of_birth": "1965-08-19",
        "age": 61,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Уборщик производственных помещений",
        "education": "среднее",
        "department_id": 19,
        "year_of_start_education": "1981",
        "year_of_end_education": "1984",
        "year_of_start_work": "1984"
    },
    {
        "id": "b582c322921f45d69e803417f8675eac",
        "second_name": "Сазонов",
        "name": "Андрей",
        "middle_name": "Феофанович",
        "adress": "г. Тикси, пер. Березовый, д. 28, 780881",
        "passport": "9984 756258",
        "email": "andrej.sazonov@company.ru",
        "date_of_birth": "1987-11-29",
        "age": 38,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Программист",
        "education": "высшее",
        "department_id": 15,
        "year_of_start_education": "2005",
        "year_of_end_education": "2009",
        "year_of_start_work": "2009"
    },
    {
        "id": "1b927fd489ea408c9bbfe42cbcb4ab23",
        "second_name": "Власов",
        "name": "Севастьян",
        "middle_name": "Васильевич",
        "adress": "г. Саянск, пер. Пожарского, д. 9 к. 422, 873131",
        "passport": "1297 556506",
        "email": "sevast'jan.vlasov@company.ru",
        "date_of_birth": "1997-07-30",
        "age": 29,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Инженер-разработчик месторождений",
        "education": "высшее",
        "department_id": 8,
        "year_of_start_education": "2015",
        "year_of_end_education": "2019",
        "year_of_start_work": "2019"
    },
    {
        "id": "7bede339af0043d4a672e569f619afea",
        "second_name": "Орехов",
        "name": "Фотий",
        "middle_name": "Иосипович",
        "adress": "п. Белгород, ул. Московская, д. 4/3 стр. 3/7, 018549",
        "passport": "1818 468489",
        "email": "fotij.orehov@company.ru",
        "date_of_birth": "2003-01-03",
        "age": 23,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Машинист подъёмника",
        "education": "среднее",
        "department_id": 11,
        "year_of_start_education": "2019",
        "year_of_end_education": "2022",
        "year_of_start_work": "2022"
    },
    {
        "id": "9c802181ad0f4e71953a1bc0994056b0",
        "second_name": "Брагин",
        "name": "Нестор",
        "middle_name": "Ааронович",
        "adress": "клх Голицыно, бул. Каштановый, д. 7/7 стр. 9/4, 351603",
        "passport": "9044 871736",
        "email": "nestor.bragin@company.ru",
        "date_of_birth": "2005-06-16",
        "age": 21,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Инженер-эколог",
        "education": "среднее",
        "department_id": 8,
        "year_of_start_education": "2021",
        "year_of_end_education": "2024",
        "year_of_start_work": "2024"
    },
    {
        "id": "529b53d5cd244b6b9a9fb43f22ea9cc3",
        "second_name": "Большаков",
        "name": "Чеслав",
        "middle_name": "Адрианович",
        "adress": "п. Асино, пр. Лесхозный, д. 11, 493772",
        "passport": "9234 487316",
        "email": "cheslav.bol'shakov@company.ru",
        "date_of_birth": "1962-05-27",
        "age": 64,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Мастер строительных работ",
        "education": "среднее",
        "department_id": 10,
        "year_of_start_education": "1978",
        "year_of_end_education": "1981",
        "year_of_start_work": "1981"
    },
    {
        "id": "e05dbceeed944cd5a139e1bf11beb6f0",
        "second_name": "Третьяков",
        "name": "Аркадий",
        "middle_name": "Данилович",
        "adress": "г. Кизел, пер. Приозерный, д. 965, 624748",
        "passport": "7211 402517",
        "email": "arkadij.tret'jakov@company.ru",
        "date_of_birth": "1959-01-06",
        "age": 67,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Специалист по охране труда",
        "education": "высшее",
        "department_id": 17,
        "year_of_start_education": "1977",
        "year_of_end_education": "1981",
        "year_of_start_work": "1981"
    },
    {
        "id": "96a1b8bf52d4403f960ab9335ec473f1",
        "second_name": "Мельников",
        "name": "Епифан",
        "middle_name": "Августович",
        "adress": "п. Добрянка, бул. Линейный, д. 3/2, 377858",
        "passport": "9195 309305",
        "email": "epifan.mel'nikov@company.ru",
        "date_of_birth": "1964-12-25",
        "age": 61,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Ведущий юрист",
        "education": "высшее",
        "department_id": 4,
        "year_of_start_education": "1982",
        "year_of_end_education": "1986",
        "year_of_start_work": "1986"
    },
    {
        "id": "ca1a9103f2b9422c9f82a53881293778",
        "second_name": "Панов",
        "name": "Андрон",
        "middle_name": "Фокич",
        "adress": "г. Охотск, пер. Фурманова, д. 9/9, 023961",
        "passport": "6161 799281",
        "email": "andron.panov@company.ru",
        "date_of_birth": "2007-05-20",
        "age": 19,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Лаборант химического анализа",
        "education": "среднее",
        "department_id": 9,
        "year_of_start_education": "2023",
        "year_of_end_education": "2026",
        "year_of_start_work": "2026"
    },
    {
        "id": "5628f79e68024351926808969048bede",
        "second_name": "Ершов",
        "name": "Эрнест",
        "middle_name": "Димитриевич",
        "adress": "г. Мыс Шмидта, бул. Астраханский, д. 277 стр. 7/4, 549169",
        "passport": "8665 859446",
        "email": "ernest.ershov@company.ru",
        "date_of_birth": "1990-09-10",
        "age": 36,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Инженер-разработчик месторождений",
        "education": "высшее",
        "department_id": 8,
        "year_of_start_education": "2008",
        "year_of_end_education": "2012",
        "year_of_start_work": "2012"
    },
    {
        "id": "e4d46b0e86a743d9bb3c83f9765f2c2f",
        "second_name": "Савельев",
        "name": "Николай",
        "middle_name": "Валерьянович",
        "adress": "ст. Тутончаны, наб. Троицкая, д. 7, 354352",
        "passport": "5103 108524",
        "email": "nikolaj.savel'ev@company.ru",
        "date_of_birth": "2008-07-31",
        "age": 18,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Старший пожарный",
        "education": "среднее",
        "department_id": 17,
        "year_of_start_education": "2024",
        "year_of_end_education": "2027",
        "year_of_start_work": "2027"
    },
    {
        "id": "e3ba88c6499841939512f703f799e0b8",
        "second_name": "Третьяков",
        "name": "Нестор",
        "middle_name": "Германович",
        "adress": "г. Усть-Джегута, пр. Садовый, д. 7/3 стр. 7, 837957",
        "passport": "1118 911845",
        "email": "nestor.tret'jakov@company.ru",
        "date_of_birth": "2002-06-09",
        "age": 24,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Специалист по охране труда",
        "education": "высшее",
        "department_id": 17,
        "year_of_start_education": "2020",
        "year_of_end_education": "2024",
        "year_of_start_work": "2024"
    },
    {
        "id": "e8a400930eef4c509040a7d8781e8745",
        "second_name": "Алексеева",
        "name": "Юлия",
        "middle_name": "Захаровна",
        "adress": "г. Верещагино (Перм.), пер. Пожарского, д. 329, 669368",
        "passport": "4378 190179",
        "email": "julija.alekseeva@company.ru",
        "date_of_birth": "2007-07-13",
        "age": 19,
        "gender": "женский",
        "marital_status": "не замужем",
        "position": "Старший пожарный",
        "education": "среднее",
        "department_id": 17,
        "year_of_start_education": "2023",
        "year_of_end_education": "2026",
        "year_of_start_work": "2026"
    },
    {
        "id": "507f21dcbd4746a6b56f3bd4f839ae6b",
        "second_name": "Гурьева",
        "name": "Светлана",
        "middle_name": "Геннадиевна",
        "adress": "п. Моздок, бул. Советский, д. 5, 259547",
        "passport": "6405 736692",
        "email": "svetlana.gur'eva@company.ru",
        "date_of_birth": "1967-10-16",
        "age": 58,
        "gender": "женский",
        "marital_status": "не замужем",
        "position": "Инженер-строитель",
        "education": "высшее",
        "department_id": 8,
        "year_of_start_education": "1985",
        "year_of_end_education": "1989",
        "year_of_start_work": "1989"
    },
    {
        "id": "0db7fa7b3b0740daa6f4e7858b720f5e",
        "second_name": "Осипов",
        "name": "Нифонт",
        "middle_name": "Валентинович",
        "adress": "д. Курчатов, ш. Черемушки, д. 1 стр. 98, 148078",
        "passport": "4924 890985",
        "email": "nifont.osipov@company.ru",
        "date_of_birth": "1995-07-24",
        "age": 31,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Ведущий HR-специалист",
        "education": "высшее",
        "department_id": 2,
        "year_of_start_education": "2013",
        "year_of_end_education": "2017",
        "year_of_start_work": "2017"
    },
    {
        "id": "a04e5109f711429a9620b448f5b56b64",
        "second_name": "Тарасов",
        "name": "Егор",
        "middle_name": "Ефимович",
        "adress": "к. Макушино, ул. Социалистическая, д. 2/3, 338403",
        "passport": "4999 161748",
        "email": "egor.tarasov@company.ru",
        "date_of_birth": "2003-08-11",
        "age": 23,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Электромонтёр",
        "education": "среднее",
        "department_id": 20,
        "year_of_start_education": "2019",
        "year_of_end_education": "2022",
        "year_of_start_work": "2022"
    },
    {
        "id": "4caa95f688ae4890968ca37ef0607591",
        "second_name": "Данилов",
        "name": "Давыд",
        "middle_name": "Федосьевич",
        "adress": "к. Люберцы, алл. Харьковская, д. 89 к. 814, 331204",
        "passport": "6062 510415",
        "email": "davyd.danilov@company.ru",
        "date_of_birth": "2001-01-19",
        "age": 25,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Инженер-исследователь",
        "education": "высшее",
        "department_id": 7,
        "year_of_start_education": "2019",
        "year_of_end_education": "2023",
        "year_of_start_work": "2023"
    },
    {
        "id": "fb73f98fcfdd4a94a42f9964817abece",
        "second_name": "Бирюков",
        "name": "Каллистрат",
        "middle_name": "Афанасьевич",
        "adress": "к. Нурлат, ш. Монтажников, д. 406, 865427",
        "passport": "4252 609459",
        "email": "kallistrat.birjukov@company.ru",
        "date_of_birth": "1991-01-07",
        "age": 35,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Ведущий специалист по безопасности",
        "education": "высшее",
        "department_id": 4,
        "year_of_start_education": "2009",
        "year_of_end_education": "2013",
        "year_of_start_work": "2013"
    },
    {
        "id": "ab1f6547373946e2875e08ffe721073a",
        "second_name": "Потапов",
        "name": "Аскольд",
        "middle_name": "Борисович",
        "adress": "к. Кирово-Чепецк, алл. Сиреневая, д. 7/8 стр. 761, 898859",
        "passport": "5446 194805",
        "email": "askol'd.potapov@company.ru",
        "date_of_birth": "1978-01-03",
        "age": 48,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Техник по охране труда",
        "education": "среднее",
        "department_id": 18,
        "year_of_start_education": "1994",
        "year_of_end_education": "1997",
        "year_of_start_work": "1997"
    },
    {
        "id": "ca8d4ee724684754839fc90af8b50350",
        "second_name": "Исаков",
        "name": "Карл",
        "middle_name": "Филимонович",
        "adress": "с. Алагир, бул. Уральский, д. 5 стр. 1/8, 472318",
        "passport": "3773 774173",
        "email": "karl.isakov@company.ru",
        "date_of_birth": "1954-09-27",
        "age": 71,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Старший пожарный",
        "education": "среднее",
        "department_id": 17,
        "year_of_start_education": "1970",
        "year_of_end_education": "1973",
        "year_of_start_work": "1973"
    },
    {
        "id": "9bb7b16e8435408ebdcd35f1c9f6d4f9",
        "second_name": "Федотова",
        "name": "Клавдия",
        "middle_name": "Альбертовна",
        "adress": "ст. Кондопога, наб. Луначарского, д. 425, 614574",
        "passport": "4812 803681",
        "email": "klavdija.fedotova@company.ru",
        "date_of_birth": "1966-11-10",
        "age": 59,
        "gender": "женский",
        "marital_status": "не замужем",
        "position": "Помощник оператора",
        "education": "среднее",
        "department_id": 14,
        "year_of_start_education": "1982",
        "year_of_end_education": "1985",
        "year_of_start_work": "1985"
    },
    {
        "id": "7e246e93ae724cf78479f86e0e5190d5",
        "second_name": "Агафонов",
        "name": "Егор",
        "middle_name": "Владиленович",
        "adress": "к. Новочеркасск, пер. Тракторный, д. 5 к. 729, 846460",
        "passport": "2609 240775",
        "email": "egor.agafonov@company.ru",
        "date_of_birth": "1981-04-17",
        "age": 45,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Оператор обессоливающей установки",
        "education": "среднее",
        "department_id": 13,
        "year_of_start_education": "1997",
        "year_of_end_education": "2000",
        "year_of_start_work": "2000"
    },
    {
        "id": "d2ebb4f75c734d56a9ec1cc3178edd9a",
        "second_name": "Федосеев",
        "name": "Ярополк",
        "middle_name": "Эдгардович",
        "adress": "клх Троицк (Моск.), наб. Интернациональная, д. 3 стр. 3, 903531",
        "passport": "3314 817725",
        "email": "jaropolk.fedoseev@company.ru",
        "date_of_birth": "1975-12-22",
        "age": 50,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Техник",
        "education": "среднее",
        "department_id": 17,
        "year_of_start_education": "1991",
        "year_of_end_education": "1994",
        "year_of_start_work": "1994"
    },
    {
        "id": "6fc90a1abecc40e892140d544eacff50",
        "second_name": "Герасимов",
        "name": "Никодим",
        "middle_name": "Борисович",
        "adress": "д. Новосибирск, ул. Ленская, д. 149 к. 60, 636791",
        "passport": "4972 995971",
        "email": "nikodim.gerasimov@company.ru",
        "date_of_birth": "1967-11-07",
        "age": 58,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Ведущий инженер-эколог",
        "education": "высшее",
        "department_id": 3,
        "year_of_start_education": "1985",
        "year_of_end_education": "1989",
        "year_of_start_work": "1989"
    },
    {
        "id": "f1093b76d4c74ff3b48590478aab8377",
        "second_name": "Маслов",
        "name": "Доброслав",
        "middle_name": "Ефимьевич",
        "adress": "д. Армавир, пер. Покровский, д. 2 к. 5, 167465",
        "passport": "4521 136576",
        "email": "dobroslav.maslov@company.ru",
        "date_of_birth": "1961-01-30",
        "age": 65,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Чертёжник",
        "education": "среднее",
        "department_id": 19,
        "year_of_start_education": "1977",
        "year_of_end_education": "1980",
        "year_of_start_work": "1980"
    },
    {
        "id": "5f538224d4974fb0993bce67cc3dd142",
        "second_name": "Князев",
        "name": "Модест",
        "middle_name": "Тихонович",
        "adress": "ст. Урюпинск, ул. Владимирская, д. 8, 118344",
        "passport": "5824 405906",
        "email": "modest.knjazev@company.ru",
        "date_of_birth": "1973-02-04",
        "age": 53,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Мастер участка",
        "education": "среднее",
        "department_id": 10,
        "year_of_start_education": "1989",
        "year_of_end_education": "1992",
        "year_of_start_work": "1992"
    },
    {
        "id": "0832fc3d4a6e4e18b466361a81c1f4c9",
        "second_name": "Гаврилов",
        "name": "Ростислав",
        "middle_name": "Дорофеевич",
        "adress": "д. Горячий Ключ, ш. Иванова, д. 3/2 стр. 47, 494241",
        "passport": "7815 998783",
        "email": "rostislav.gavrilov@company.ru",
        "date_of_birth": "2007-02-13",
        "age": 19,
        "gender": "мужской",
        "marital_status": "женат",
        "position": "Инженер-электроник",
        "education": "среднее",
        "department_id": 9,
        "year_of_start_education": "2023",
        "year_of_end_education": "2026",
        "year_of_start_work": "2026"
    },
    {
        "id": "01780948733a4d529daa1428ce03d4fe",
        "second_name": "Сорокин",
        "name": "Парамон",
        "middle_name": "Эдуардович",
        "adress": "к. Челюскин, алл. Ломоносова, д. 49, 624875",
        "passport": "4522 358126",
        "email": "paramon.sorokin@company.ru",
        "date_of_birth": "1985-05-24",
        "age": 41,
        "gender": "мужской",
        "marital_status": "холост",
        "position": "Ведущий инженер-эколог",
        "education": "высшее",
        "department_id": 3,
        "year_of_start_education": "2003",
        "year_of_end_education": "2007",
        "year_of_start_work": "2007"
    }
]


export const departamentsData = {
    "0": {
        "name": "Цех добычи нефти и газа (ЦДНГ)",
        "adress": "д. Приозерск, пр. Набережный, д. 65, 746144",
        "phone": "87540703715"
    },
    "1": {
        "name": "Цех поддержания пластового давления (ЦППД)",
        "adress": "к. Кировск (Мурм.), ул. Кавказская, д. 941, 620783",
        "phone": "85787669982"
    },
    "2": {
        "name": "Цех подготовки и перекачки нефти (ЦППН)",
        "adress": "клх Нижний Новгород, пер. Амурский, д. 5/9 стр. 763, 340949",
        "phone": "87563737737"
    },
    "3": {
        "name": "Управление буровых работ (УБР)",
        "adress": "клх Саранск, ул. Студенческая, д. 667 стр. 7, 942170",
        "phone": "82023789878"
    },
    "4": {
        "name": "Цех капитального ремонта скважин (ЦКРС)",
        "adress": "к. Городовиковск, бул. Нагорный, д. 10 стр. 76, 180182",
        "phone": "81696517384"
    },
    "5": {
        "name": "Цех текущего ремонта скважин (ЦТРС)",
        "adress": "клх Тайшет, алл. Бульварная, д. 597, 394285",
        "phone": "82497454359"
    },
    "6": {
        "name": "Промыслово-геофизическое управление (ПГУ)",
        "adress": "с. Верхоянск, пр. Клубный, д. 27, 597721",
        "phone": "81910746867"
    },
    "7": {
        "name": "Цех автоматизации и метрологии (ЦАиМ)",
        "adress": "п. Ялуторовск, бул. Черняховского, д. 5 к. 3, 909161",
        "phone": "86729441428"
    },
    "8": {
        "name": "Геологический отдел",
        "adress": "к. Шали, ул. Полевая, д. 158, 993209",
        "phone": "85823225838"
    },
    "9": {
        "name": "Отдел разработки месторождений",
        "adress": "к. Теберда, пер. 8-е Марта, д. 690 к. 249, 946600",
        "phone": "89568442816"
    },
    "10": {
        "name": "Проектный институт / отдел проектирования",
        "adress": "д. Бугульма, алл. Ленина, д. 1/3 к. 37, 589882",
        "phone": "87264592204"
    },
    "11": {
        "name": "Отдел капитального строительства (ОКС)",
        "adress": "д. Глазов, алл. Стахановская, д. 99 стр. 84, 132941",
        "phone": "83665273736"
    },
    "12": {
        "name": "Отдел главного механика",
        "adress": "д. Снежногорск (Мурм.), наб. Дорожников, д. 4/4 к. 6/2, 534212",
        "phone": "86276534672"
    },
    "13": {
        "name": "Отдел главного энергетика",
        "adress": "клх Елатьма, ул. Троицкая, д. 691, 456966",
        "phone": "84283503455"
    },
    "14": {
        "name": "Служба охраны труда и промышленной безопасности",
        "adress": "клх Кинешма, алл. Войкова, д. 585, 762147",
        "phone": "82766487959"
    },
    "15": {
        "name": "Экологическая служба",
        "adress": "д. Черняховск, бул. Центральный, д. 1/8 к. 71, 344776",
        "phone": "87195105528"
    },
    "16": {
        "name": "Пожарная охрана",
        "adress": "к. Невельск, ш. Светлое, д. 8 к. 1, 679399",
        "phone": "84810718104"
    },
    "17": {
        "name": "Служба корпоративной безопасности",
        "adress": "г. Кежма, пер. Морозова, д. 8/7 к. 9/8, 842026",
        "phone": "87153831619"
    },
    "18": {
        "name": "Планово-экономический отдел (ПЭО)",
        "adress": "клх Городовиковск, ул. Стадионная, д. 9/4 к. 636, 712848",
        "phone": "88298012932"
    },
    "19": {
        "name": "Финансовый отдел / бухгалтерия",
        "adress": "к. Щельяюр, ул. Промышленная, д. 3 стр. 3/2, 601159",
        "phone": "89070493759"
    },
    "20": {
        "name": "Отдел закупок / МТС",
        "adress": "к. Владикавказ, наб. Сурикова, д. 46 стр. 8, 664152",
        "phone": "82461589458"
    },
    "21": {
        "name": "Отдел логистики",
        "adress": "ст. Далматово, ш. Свободы, д. 8/5, 829915",
        "phone": "89662138320"
    },
    "22": {
        "name": "Юридический отдел",
        "adress": "к. Южно-Сахалинск, бул. Воровского, д. 5 к. 1, 804586",
        "phone": "84649634123"
    },
    "23": {
        "name": "Отдел кадров / управление персоналом",
        "adress": "ст. Курильск, алл. Высокая, д. 5/8, 010483",
        "phone": "88217699289"
    },
    "24": {
        "name": "Отдел информационных технологий (ИТ)",
        "adress": "с. Гремячинск (Бурят.), пер. Депутатский, д. 2 стр. 1/7, 481434",
        "phone": "89858312529"
    },
    "25": {
        "name": "Отдел экономического анализа и развития",
        "adress": "ст. Балашиха, наб. Лазурная, д. 882 к. 8, 020247",
        "phone": "85317423473"
    },
    "26": {
        "name": "Управление инноваций / НИОКР",
        "adress": "ст. Каспийск, бул. Революции, д. 6 к. 4, 876340",
        "phone": "89559423857"
    },
    "27": {
        "name": "Отдел геолого-технического моделирования",
        "adress": "ст. Ялуторовск, алл. Щетинкина, д. 87 к. 7/9, 534773",
        "phone": "85401319119"
    },
    "28": {
        "name": "Корпоративный центр",
        "adress": "д. Сасово, пр. Приозерный, д. 8/7 стр. 99, 238197",
        "phone": "87312692800"
    }
}